#google
spring:
  security:
    oauth2.client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
            - profile
            - email
            - gender

          naver:
            client-id:
            client-secret:
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: {baseUrl}/{action}/oauth2/code/{registrationId}
            scope:
            - name
            - email
            - profile_image
            - gender
            client-name: Naver

          kakao:
            client-id:
            client-secret:
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: { baseUrl }/{action}/oauth2/code/{registrationId}
            scope:
            - profile_nickname
            - profile_image
            - account_email
            - gender
            client-name: Kakao

        #Provider 설정
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
# cors 설정
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect